Garaje/Controllers/CartController.cs
using BusinessLogicLayer.Interfacaces;
using DateAccess.Data;
using DateAccess.Models;
using Garaje.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace Garaje.Controllers
{
    [Authorize]
    
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        public CartController(ICartService cartService)
        {           
            _cartService = cartService;
        }

        //дозволяє бачити цю функцію без регістрації
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_cartService.GetAllCart());
        }

        //[Authorize(Roles = "User,Admin")]
        public IActionResult Add(int id)
        {
            _cartService.Add(id);
            return RedirectToAction(nameof(Index), "Home");
        }

        public IActionResult Remove(int id)
        {
            _cartService.Remove(id);
            return RedirectToAction(nameof(Index), "Home");
        }
    }
}

Garaje/Controllers/OrderController.cs
using BusinessLogicLayer.CarService;
using BusinessLogicLayer.Interfacaces;
using DateAccess.Data;
using DateAccess.Models;
using Garaje.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Text.Json;

namespace Garaje.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        public OrderController(IOrderService orderService) 
        {
            _orderService = orderService;
        }
        public IActionResult Index()
        {
            string userId=User.FindFirstValue(ClaimTypes.NameIdentifier);

            var orders = _orderService.GetAll(userId);

            return View(orders);
        }

        public IActionResult CreateOrder()
        {
            //витагуємо авторизованого на сайті користувача за допомогою команди User
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            List<int> idList = HttpContext.Session.GetObject<List<int>>("mycart");

            _orderService.Create(userId, idList);

            //очищаємо сесію. Тобто усі дії користувача на сторінці
            HttpContext.Session.Remove("mycart");

            return RedirectToAction(nameof(Index));
        }
    }
}

Garaje/Controllers/StorageController.cs
using BusinessLogicLayer.Interfacaces;
using BusinessLogicLayer.CarService;
using Microsoft.AspNetCore.Mvc;

namespace Garaje.Controllers
{
    public class StorageController : Controller
    {
        private readonly IStorageService _storageService;

        public StorageController(IStorageService storageService)
        {
            _storageService = storageService;
        }

        public IActionResult Index()
        {
            var storage = _storageService.GetAllStorage();

            return View(storage);
        }
    }
}

Garaje/Views/Shared/_CartCarView.cshtml
@model CarCartViewModel

@{
    string carImagePlaceholder = @"https://www.freeiconspng.com/thumbs/no-image-icon/no-image-icon-15.png";
}

<div class="col-sm-4">
    <div class="card">
               
         <div class="product-card-img">
            <img src="~/Images/@Model.Car.ImagePath" class="card-img-top" alt="...">
        </div>
        
        <div class="card-body">
            <h5 class="card-title">@Model.Car.ModelCar</h5>           
            <p class="card-text">@Model.Car.ColorCar</p>
            <p class="fw-bold">Price <span class="badge bg-primary">@Model.Car.Price</span></p>
            <p class="fw-bold">Кількість<span class="badge bg-primary">@Model.Car.Quantity</span></p>
            <a asp-controller="Home" asp-action="Details" asp-route-id=@Model.Car.Id class="btn btn-dark">Деталі</a>
           
            @if(Model.Car.Quantity>0)
            {        
            
            <a asp-controller="Home" asp-action="Delete" asp-route-id=@Model.Car.Id class="btn btn-danger">Видалити</a>
            <a asp-controller="Home" asp-action="Edit" asp-route-id=@Model.Car.Id class="btn btn-success">Редагувати</a>

            @if (!Model.IsCarChoose)
            {
                <a asp-controller="Cart" asp-action="Add" asp-route-id=@Model.Car.Id class="btn btn-info">Додати в корзину</a>
            }
            else
            {
                <a asp-controller="Cart" asp-action="Remove" asp-route-id=@Model.Car.Id class="btn btn-secondary">Видалити з корзини</a>
                }

            }
            else
            {
                <h3>Немає у наявності</h3>
            }

        </div>
    </div>
</div>

Garaje/Views/Shared/_Layout.cshtml
@using DateAccess.Models;
@using Garaje.Helper;
@using Microsoft.AspNetCore.Identity;

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Garaje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*підключаємо фото*@
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Garaje.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Garaje</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                      
                  <ul class="navbar-nav flex-grow-1">

                    @*Якщо користувач авторизований, то кнопка замовлення відображається*@
                      
                   @* @if (SignInManager.IsSignedIn(User))
                     {*@

                    <li class="nav-item">

                    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Замовлення</a>                         
                           
                    </li>
                    @*}*@

                  <li class="nav-item">

                 <a class="nav-link text-dark" asp-area="" asp-controller="Storage" asp-action="Index">Гараж</a>

                  </li>

                  <li class="nav-item">

                     @* обчислюємо кількість вибраних авто в корзину*@
                            @{
                                var listCarInCart = Context.Session.GetObject<List<int>>("mycart");
                            }

                 <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                                Корзина <i class="bi bi-car-front-fill"></i> 
                              @*  функція обрахунку кількості авто. Якщо нічого не вибрано, то показує 0*@
                                @(listCarInCart?.Count??0)
                                
                                </a>
                   
                  </li>

                       
                      </ul>

                      @*для вбудовування частинки коду Тут ми вбудували реєстрацію*@
                      <partial name="_LoginPartial"/>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Garaje - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>